### ISSUE TITLE
Add AUP features included in v1.9.0

### ISSUE THREAD

**Issue by federicaagostini** [andreaceccanti/iam-website#116]
In particular:
- VO members can resign the AUP at any time: PR https://github.com/indigo-iam/iam/pull/757
- allow to delete a signature and also sign on behalf of the user: PR https://github.com/indigo-iam/iam/pull/777
- in case AUP screenshots are shown in this documentation, replace them with the ones displaying how much time is left until expiration (PR https://github.com/indigo-iam/iam/pull/783) rather than when it was signed last time.

**Comment by enricovianello** [comment]
We should also update the AUP signature API page.
