### ISSUE TITLE
Dead link on getting-started/docker

### ISSUE THREAD

**Issue by pablo-de-andres** [andreaceccanti/iam-website#6]
I am looking into deploying the IAM service, and wanted to look into Docker for flexibility.
The [documentation page](https://indigo-iam.github.io/v/v1.7.1/docs/getting-started/docker/) points to a configuration reference, but the link is dead:
> See [the configuration reference](https://indigo-iam.github.io/docs/reference/configuration) for a description of the variables.

**Comment by pablo-de-andres** [comment]
I believe the link is just missing the versioning path and instead of:
https://indigo-iam.github.io/docs/reference/configuration/
should be:
https://indigo-iam.github.io/v/v1.7.1/docs/reference/configuration/

**Comment by andreaceccanti** [comment]
Thanks a lot Pablo for reporting this, I've just committed a fix, the problem should be solved shortly !
